<?php
/**
 * @file
 * Drupal needs this blank file.
 */

/**
 * Implements hook_enable().
 */
function uoe_devel_enable() {
  variable_set('features_default_export_path', 'sites/all/modules/features');
}

/**
 * Helper function to output query string with the placeholders replaced with
 * the arguments.
 */
function uoe_devel_get_query_string(SelectQueryInterface $query) {
  $string = (string) $query;
  $arguments = $query->arguments();

  if (!empty($arguments) && is_array($arguments)) {
    foreach ($arguments as $placeholder => &$value) {
      if (is_string($value)) {
        $value = "'$value'";
      }
    }

    $string = strtr($string, $arguments);
  }

  // Put in the table prefixes.
  return Database::getConnection()->prefixTables($string);
}
